service: FindPhrase

image: jibrankalia/find-phrase

servers:
  web:
    - 5.78.67.11
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

proxy:
  ssl: true
  host: findthephrase.com

registry:
  username: jibrankalia
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: 5.78.67.11
    DB_NAME: findthephrase
    DB_USERNAME: findthephrase
    DB_PORT: 5433
    WEB_CONCURRENCY: 2
    RAILS_LOG_LEVEL: info
    RAILS_SERVE_STATIC_FILES: true

volumes:
  - "/mnt/HC_Volume_103056667/find-phrase-storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  remote: ssh://app@5.78.67.11

  args:
    RUBY_VERSION: 3.3.8
  secrets:
    - GITHUB_TOKEN
    - RAILS_MASTER_KEY

accessories:
  postgres:
    image: postgres:17
    host: 5.78.67.11
    port: 5433:5432
    env:
      secret:
        - POSTGRES_PASSWORD
      clear:
        POSTGRES_USER: findthephrase
        POSTGRES_DB: findthephrase
    volumes:
      - /mnt/HC_Volume_103056667/find-phrase-postgres-data:/var/lib/postgresql/data

ssh:
  user: app
